### ISSUE TITLE
Mogelijke repo toevoegingen

### ISSUE THREAD

**Issue by lennartdeknikker** [ManoukK/Frontend-data#3]
- je .gitignore bestand is erg uitgebreid. Ik weet niet of het allemaal nodig is. Zelf heb ik alleen de bestanden toegevoegd die aanwezig waren in de map, maar op deze manier ben je wel zeker dat er nooit iets onnodigs in je repo komt.
- Je hebt nog geen description of link naar live demo.
- Je concept is duidelijk omschreven. Wanneer je klaar bent kun je de afbeelding nog vervangen met een screenshot van je eigen applicatie
- Je hebt je bronnen wel vermeld, maar je zou misschien nog een keer onder een apart kopje ze kunnen opsommen.
- Welke data je hebt gebruikt is duidelijk omschreven.

**Comment by ManoukK** [comment]
Alle stukjes op verdeelt in nieuwe issues
