### ISSUE TITLE
Mogelijke toevoegingen voor je wiki

### ISSUE THREAD

**Issue by lennartdeknikker** [ManoukK/Frontend-data#4]
- [ ] Je enter-exit-update pattern moet je nog toevoegen, maar daar heb je wel al een pagina voor.
- [ ] Je documentatie over werken met d3 is al goed compleet. Je zou nog iets meer losse regels van je code kunnen toelichten, want je hebt nu op veel plaatsen hele blokken in een keer neergezet.

**Comment by ManoukK** [comment]
Ik heb hier twee losse issues van gemaakt
