### ISSUE TITLE
Peer review concept

### ISSUE THREAD

**Issue by lennartdeknikker** [ManoukK/Frontend-data#5]
- [ ] Je visualisatie laat goed zien hoe de collectie is verdeeld. Je zou de categorieën nog een beetje kunnen sorteren, zodat wapens en strijd en oorlog bijvoorbeeld naast elkaar staan.  

- [ ] Wel mooi dat je kunt filteren op verschillende werelddelen. Alleen is het een beetje onlogisch hoe de bars zijn opgebouwd. de verschillende delen van de bars zijn niet van groot naar klein opgestapeld, maar ook niet in een vaste volgorde.

- [ ] Je zou ook nog symbooltjes aan de verschillende categorieën toevoegen om het sneller te kunnen interpreteren, maar dat is misschien wel veel werk.
- [ ] De interactie heb ik nog niet goed kunnen bekijken, omdat ik geen live versie van je applicatie kon bekijken.

**Comment by ManoukK** [comment]
alle onderdelen in aparte issues gezet. Behalve de laatste, die issue had ik al
