### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by lennartdeknikker** [ManoukK/Frontend-data#6]
- [ ] Je hebt nog niet veel code in je repo staan. Volgens mij alleen het voorbeeld? De code die in je wiki staat is consistent en heb je daar wel duidelijk geannoteerd. Ook op Vizhub ziet het er netjes uit. De interactie werkt helaas nog niet, maar daar ben je nu wel al mee bezig geloof ik.

**Comment by ManoukK** [comment]
Als het goed is, is dit nu gefixed omdat ik nu mijn juiste, up to date code in mijn repo heb staan
